openapi: 3.0.0
info:
  title: Authenticated Tasks API
  version: 1.0.0
servers:
  - url: http://localhost:8000
paths:
  /api/tasks:
    get:
      security:
        - bearerAuth: []
      responses:
        '200':
          description: User tasks
        '401':
          description: Unauthorized
    post:
      security:
        - bearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskCreate'
      responses:
        '201':
          description: Created task
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Task:
      type: object
      properties:
        id: {type: string, format: uuid}
        title: {type: string}
        description: {type: string}
        completed: {type: boolean}
        user_id: {type: string, format: uuid, readOnly: true}
    TaskCreate:
      type: object
      required: [title]
      properties:
        title: {type: string}
        description: {type: string}
        completed: {type: boolean}
